# Generated by Django 4.2.2 on 2023-06-12 18:20

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slugged_name', models.SlugField(max_length=300, unique=True)),
                ('photo', models.ImageField(upload_to='movies/images/', validators=[movies.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slugged_name', models.SlugField(max_length=300, unique=True)),
                ('photo', models.ImageField(upload_to='movies/images/', validators=[movies.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('country', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('PL', 'Poland'), ('CA', 'Canada'), ('IT', 'Italy'), ('JP', 'Japan'), ('CN', 'China')], max_length=2)),
                ('poster', models.ImageField(upload_to='movies/images', validators=[movies.models.validate_file_size])),
                ('actors', models.ManyToManyField(to='movies.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.director')),
            ],
        ),
    ]
