# Generated by Django 4.2.4 on 2023-08-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movies.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of genres.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='genres'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'owner')},
        ),
    ]
