# Generated by Django 4.2.2 on 2023-06-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
    ]
